export const BLOCKCHAIN_NETWORKS = [
  // Ethereum & Testnets
  { name: 'Ethereum Mainnet', chainId: 1 },
  { name: 'Ropsten Testnet', chainId: 3 },
  { name: 'Rinkeby Testnet', chainId: 4 },
  { name: 'Goerli Testnet', chainId: 5 },
  { name: 'Kovan Testnet', chainId: 42 },
  { name: 'Sepolia Testnet', chainId: 11155111 },
  { name: 'Holesky Testnet', chainId: 17000 },
  { name: 'Hoodi Testnet', chainId: 560048 },

  // Binance Smart Chain
  { name: 'BSC Mainnet', chainId: 56 },
  { name: 'BSC Testnet', chainId: 97 },

  // Polygon
  { name: 'Polygon Mainnet', chainId: 137 },
  { name: 'Mumbai Testnet', chainId: 80001 },

  // Avalanche
  { name: 'Avalanche C-Chain', chainId: 43114 },
  { name: 'Fuji Testnet', chainId: 43113 },

  // Fantom
  { name: 'Fantom Opera', chainId: 250 },
  { name: 'Fantom Testnet', chainId: 4002 },

  // Arbitrum
  { name: 'Arbitrum One', chainId: 42161 },
  { name: 'Arbitrum Goerli', chainId: 421613 },

  // Optimism
  { name: 'Optimism Mainnet', chainId: 10 },
  { name: 'Optimism Goerli', chainId: 420 },

  // Gnosis (xDai)
  { name: 'Gnosis Chain', chainId: 100 },
  { name: 'Chiado Testnet', chainId: 10200 },

  // Additional EVM-compatible networks
  { name: 'Avalanche Fuji Testnet', chainId: 43113 },
  { name: 'Arbitrum Nova', chainId: 42170 },
  { name: 'Moonbeam', chainId: 1284 },
  { name: 'Moonriver', chainId: 1285 },
  { name: 'Fantom Testnet', chainId: 4002 },
  { name: 'Cronos Mainnet', chainId: 25 },
  { name: 'Cronos Testnet', chainId: 338 },
  { name: 'Telos EVM', chainId: 40 },
  { name: 'IoTeX Network', chainId: 4689 },
  { name: 'OKXChain', chainId: 66 },
  { name: 'Velas EVM', chainId: 106 },
  { name: 'Metis Andromeda', chainId: 1088 },
  { name: 'Metis Stardust Testnet', chainId: 588 },
  { name: 'Boba Network', chainId: 288 },
  { name: 'Fuse Network', chainId: 122 },
  { name: 'Elastos Smart Chain', chainId: 20 },
  { name: 'Oasis Emerald', chainId: 42262 },
  { name: 'KCC Mainnet', chainId: 321 },
  { name: 'BitTorrent Chain', chainId: 199 },
  { name: 'CoinEx Smart Chain', chainId: 52 },
  { name: 'Theta Mainnet', chainId: 361 },
  { name: 'Nahmii Mainnet', chainId: 5551 },
  { name: 'Ethereum Classic', chainId: 61 },
  { name: 'Energi Mainnet', chainId: 39797 },
  { name: 'Bitgert Mainnet', chainId: 32520 },
  { name: 'Crab Network', chainId: 44 },
  { name: 'Energy Web Chain', chainId: 246 },
  { name: 'Nova Network', chainId: 87 },
  { name: 'Shiden', chainId: 336 },
  { name: 'Callisto Mainnet', chainId: 820 },
  { name: 'Ontology Mainnet', chainId: 58 },
  { name: 'Zyx Mainnet', chainId: 55 },
  { name: 'Findora Mainnet', chainId: 2152 },
  { name: 'TomoChain', chainId: 88 },
  { name: 'Syscoin Mainnet', chainId: 57 },
  { name: 'Ubiq', chainId: 8 },
  { name: 'LACHAIN Mainnet', chainId: 225 },
  { name: 'Lightlink Phoenix', chainId: 1890 },
  { name: 'Milkomeda A1', chainId: 2002 },
  { name: 'High Performance Blockchain', chainId: 269 },
  { name: 'Cube Chain', chainId: 1818 },
  { name: 'GoChain', chainId: 60 },
  { name: 'REI Network', chainId: 47805 },
  { name: 'IVAR Chain', chainId: 88888 },
  { name: 'Mode', chainId: 34443 },
  { name: 'REI Chain', chainId: 55555 },
  { name: 'Palm', chainId: 11297108109 },
  { name: 'Expanse Network', chainId: 2 },
  { name: 'Ropsten', chainId: 3 },
  { name: 'Rinkeby', chainId: 4 },
  { name: 'Goerli', chainId: 5 },
  { name: 'Conflux eSpace', chainId: 71 },
  { name: 'DxChain Testnet', chainId: 72 },
  { name: 'FNCY', chainId: 73 },
  { name: 'IDChain Mainnet', chainId: 74 },
  { name: 'Decimal Smart Chain', chainId: 75 },
  { name: 'Mix', chainId: 76 },
  { name: 'HOO Smart Chain Testnet', chainId: 170 },
  { name: 'Latam-Blockchain Resil Testnet', chainId: 172 },
  { name: 'AME Chain Mainnet', chainId: 180 },
  { name: 'Seele Mainnet', chainId: 186 },
  { name: 'BMC Mainnet', chainId: 188 },
  { name: 'TOP Mainnet EVM', chainId: 980 },
  { name: 'Memo Smart Chain', chainId: 985 },
  { name: 'TOP Mainnet', chainId: 989 },
  { name: 'eLiberty Mainnet', chainId: 990 },
  { name: '5ireChain Thunder', chainId: 997 },
  { name: 'Lucky Network', chainId: 998 },
  { name: 'TBSI Testnet', chainId: 1708 },
  { name: 'Palette Chain', chainId: 1718 },
  { name: 'PartyChain', chainId: 1773 },
  { name: 'Gauss Mainnet', chainId: 1777 },
  { name: 'Kerleano', chainId: 1804 },
  { name: 'Rabbit Analog Testnet', chainId: 1807 },
  { name: 'Cube Chain Testnet', chainId: 1819 },
  { name: 'Ruby Smart Chain', chainId: 1821 },
  { name: 'Teslafunds', chainId: 1856 },
  { name: 'WhiteBIT Network', chainId: 1875 },
  { name: 'Gitshock Cartenz Testnet', chainId: 1881 },
  { name: 'Chain ID 1909', chainId: 1909 },
  { name: 'Chain ID 1911', chainId: 1911 },
  { name: 'Chain ID 1912', chainId: 1912 },
  { name: 'ONUS Chain Testnet', chainId: 1945 },
  { name: 'D-Chain Mainnet', chainId: 1951 },
  { name: 'Dexilla Testnet', chainId: 1954 },
];
